# Generated by Django 2.2.5 on 2019-11-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191105_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCode', models.CharField(max_length=200)),
                ('SubName', models.CharField(max_length=200)),
                ('TCode', models.CharField(max_length=200)),
                ('TeacherName', models.CharField(max_length=200)),
                ('Dept', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCode', models.CharField(max_length=200)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Img', models.ImageField(upload_to='images/')),
                ('Xls', models.FileField(blank=True, upload_to='results/')),
            ],
        ),
    ]
