# Generated by Django 2.2.5 on 2019-11-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_info_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Xls',
            field=models.FileField(blank=True, upload_to='output/'),
        ),
    ]
