# Generated by Django 2.2.5 on 2019-11-21 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20191119_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='record',
            name='SubCode',
        ),
        migrations.RemoveField(
            model_name='record',
            name='Xls',
        ),
    ]
