# Generated by Django 2.2.5 on 2019-11-21 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191121_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='Date',
        ),
        migrations.AddField(
            model_name='record',
            name='Upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
